name: 🚀 Deploy website on push
on:
  push:
    branches:
      - acceptance

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      server-dir: /acc.johndeguise.com/
    secrets: inherit
