name: 🚀 Deploy website on push
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      server-dir: /stg.johndeguise.com/
    secrets: inherit
